---
title: "Untitled"
author: "Shane Halloran"
date: "30 January 2016"
output: pdf_document
---


```{r}
library(ggplot2)
library(ggthemes)
library(stringr)
library(sqldf)
library(reshape2)

#A function which takes in a datasetname, modelname and filePath, and then outputs a table:
#descstring, arc?, learning?, reg?, %

likePieChart<-function(dataName,modelName, filePath){
  file1 = file(description = filePath, open='r' ) 
  lines = readLines(file1)
  
  df1=data.frame(0,0)
for(line in lines){
  #if(grepl('\\:\\s(\\w+)$', line)){
  if(grepl('\\:',line)){
    hypName = str_extract(pattern = '\\:(\\s+\\w+)*', string = line)
    hypName=gsub(pattern = ': ', replacement = '',x = hypName)
    hypPercentage = str_extract(pattern = '^\\d+\\.\\d+', string = line)
    hypPercentage = as.numeric(hypPercentage)
    df1 = rbind(df1, c(hypName,hypPercentage))
    }
  }
  df1=df1[-1,]
df1<-cbind(df1,0,0,0)
  names(df1) = c('Component','Percent','Architecture','Learning', 'Regularizaton')
  df1$Percent<-as.numeric(df1$Percent)

  archHyps<-c('numLayers','layerSize','numConv','numFull','kW1','kW2','kW3','nF1','nF2','nF3')
  learnHyps<-c('learningRate', 'learningRateDecay', 'sequenceLength')
  regHyps<-c('maxInNorm','momentum', 'carryOverProb')
  #Loop through each row..
  for(i in 1:nrow(df1)){
    componentName<-df1[i,1]
    
    #Loop through each element in each group..
    #Architecture
    for(name2 in archHyps){
      if(grepl(name2,componentName)){
        df1[i,3]=1
      }
    }
    for(name2 in learnHyps){
      if(grepl(name2,componentName)){
        df1[i,4]=1
      }
    }
    for(name2 in regHyps){
      if(grepl(name2,componentName)){
        df1[i,5]=1
      }
    }
    
  }

  
  #table1<-sqldf("SELECT * from df1 where ")
  
  #return(df1)
  #return(df1[,((df1$Component=='numLayers')|Component=='numFull'|Component=='numConv'|Component=='kW1'|Component=='kW2'|Component=='kW3'|Component=='nF1'|Component=='nF2'|Component=='nF3'|Component=='layerSize')])

  (architecturePercent<-as.numeric(sqldf('select SUM(Percent) from df1 where architecture=1 AND learning=0 AND Regularizaton=0')))
  (learningPercent<-as.numeric(sqldf('select SUM(Percent) from df1 where architecture=0 AND learning=1 AND Regularizaton=0')))
  (regularizationPercent<-as.numeric(sqldf('select SUM(Percent) from df1 where architecture=0 AND learning=0 AND Regularizaton=1')))
  (interactions=100-(architecturePercent+learningPercent+regularizationPercent))
    
  groupedFanova = c(dataName,modelName,architecturePercent,learningPercent, regularizationPercent, interactions)
  names(groupedFanova) = c('Dataset','Model','Architecture', 'Learning', 'Regularization', 'Interactions')
  return(groupedFanova)
}
```

```{r}
df1 = rbind(
  likePieChart('Opp.','DNN', "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/25janOPPDNN4/variableImportances.txtreplaced.txt"),
  likePieChart('Opp.','CNN', "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/25janOPPCNN4/variableImportances.txtreplaced.txt"),
  likePieChart('Opp.','LSTM-F',"/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/25janOPPRNNFBF4/variableImportances.txtreplaced.txt"),
  likePieChart('Opp.','LSTM-S',"/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/25janOPPRNNSBS4/variableImportances.txtreplaced.txt"),
  likePieChart('Opp.','b-LSTM-S', "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/1febOPPBRNN4/variableImportances.txtreplaced.txt"),
  
  likePieChart('P2','DNN', "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/25janPAMAPDNN4/variableImportances.txtreplaced.txt"),
  likePieChart('P2','CNN',"/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/25janPAMAPCNN4/variableImportances.txtreplaced.txt"),
  likePieChart('P2', 'LSTM-F', "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/25janPAMAPRNNFBF4/variableImportances.txtreplaced.txt"),
  likePieChart('P2','LSTM-S', "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/25janPAMAPRNNSBS4/variableImportances.txtreplaced.txt"),
  likePieChart('P2','b-LSTM-S', "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/1febPAMAPBRNN4/variableImportances.txtreplaced.txt"),
  
  likePieChart('DG','DNN', "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/25janDGDNN4/variableImportances.txtreplaced.txt"),
  likePieChart('DG','CNN', "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/25janDGCNN4/variableImportances.txtreplaced.txt"),
  likePieChart('DG','LSTM-F', "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/25janDGRNNFBF4/variableImportances.txtreplaced.txt"),
  likePieChart('DG','LSTM-S', "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/25janDGRNNSBS4/variableImportances.txtreplaced.txt"),
  likePieChart('DG','b-LSTM-S', "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/1febDGBRNN4/variableImportances.txtreplaced.txt")
  )

df1 = melt(as.data.frame(df1), id.vars=c('Dataset','Model'))
names(df1) = c('Dataset','Model','Component','Percent')
df1$Percent=as.numeric(df1$Percent)

#gs.pal <- colorRampPalette(c("red","blue"),bias=.1,space="rgb")
```

```{r}

ggplot(data=df1, aes(x=Model, y=Percent, fill=Component)) +
    geom_bar(stat="identity") + facet_grid(Dataset~.)+ theme(axis.text.x = element_text(angle = 30, hjust = 1))+
  coord_flip()+labs(y='Percent effect on overall model variance')

#Bars grouped the other way:
#pdf('30jangroupsCrryOverProbIsInReg.pdf',width=6,height=4)

df1$Model = factor(df1$Model, levels=c('DNN','CNN','LSTM-F', 'LSTM-S', 'b-LSTM-S'), ordered = TRUE)
df1$Dataset = factor(df1$Dataset, levels=c('Opp.','P2','DG'), ordered=TRUE)

ggplot(data=df1, aes(x=Dataset, y=Percent, fill=Component)) + geom_bar(stat="identity") + facet_grid(~Model)+ theme(axis.text.x = element_text(angle = 40, hjust = 1), legend.key.size = unit(0.3, "cm"),axis.title.x = element_blank(),axis.text.y = element_text(hjust = 1,family='Helvetica', color='black', size = 12))+ guides(fill=guide_legend(title='',family='Helvetica', color='black', size = 12                                                                                                                                                                                     ))+labs(y='% effect on overall model variance',family='Helvetica', color='black', size = 9)+theme(legend.position="bottom")  #+coord_flip()#

#dev.off()
```
