---
title: "fANOVA pie charts"
author: "Shane Halloran"
date: "20 January 2016"
output: pdf_document
---
```{r,echo=FALSE}
makePieChartFromFanovaOutput<-function(file1){
  
  lines = readLines(file1)
  library(stringr)
  
  toPlot=data.frame(0,0)
  for(line in lines){
    if(grepl('\\:\\s(\\w+)$', line)){
      mi = str_extract(pattern = '\\:\\s(\\w+)$', string = line)
      mi=gsub(pattern = ': ', replacement = '',x = mi)
      mj = str_extract(pattern = '^\\d+\\.\\d+', string = line)
      mj = as.numeric(mj)
      print(c(mi,mj))
      toPlot = rbind(toPlot, c(mi,mj))
    }
  }
  toPlot=toPlot[-1,]
  names(toPlot) = c('component','percent')
  toPlot$percent<-as.numeric(toPlot$percent)
  toPlot
  higherOrder<-100-sum(toPlot$percent)
  higherOrder
  toPlot<-rbind(toPlot, c('HigherOrder', higherOrder))
  toPlot$percent<-as.numeric(toPlot$percent)
  
  substrRight <- function(x, n){
    substr(x, nchar(x)-n+1, nchar(x))
  }
  
  shortfilename = substrRight(file1, 50)
  toPlot
  pie(x=toPlot$percent, labels=toPlot$component, main=shortfilename)
  }
```

Opportunity
===
DNNs
---
```{r}
file1 = file(description = "/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/18janfANOVAresults/18janOPPDNN4/variableImportances.txtreplaced.txt", open='r' ) 
makePieChartFromFanovaOutput(file1)
```

CNNs
---
```{r}
file2<-"/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/18janfANOVAresults/18janOPPCNN4/variableImportances.txt"
makePieChartFromFanovaOutput(file2)
```

RNNFBF
---
```{r}
file1<-"/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/18janfANOVAresults/18janOPPRNNFBF4/variableImportances.txtreplaced.txt"
makePieChartFromFanovaOutput(file1)
```

RNNSBS
---
```{r}
file1<-"/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/18janfANOVAresults/18janOPPRNNSBS4/variableImportances.txtreplaced.txt"
makePieChartFromFanovaOutput(file1)
```

PAMAP2
===
DNN
---
```{r}
file1<-"/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/18janfANOVAresults/18janPAMAPDNN4/variableImportances.txtreplaced.txt"
makePieChartFromFanovaOutput(file1)
```

CNN
---
```{r}
file1="/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/18janfANOVAresults/18janPAMAPCNN4/variableImportances.txt"
makePieChartFromFanovaOutput(file1)
```

RNNFBF
---
```{r}
file1="/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/18janfANOVAresults/18janPAMAPRNNFBF4/variableImportances.txtreplaced.txt"
makePieChartFromFanovaOutput(file1)
```

RNNSBS
---
```{r}
file1="/Users/shanework/Desktop/hulk/home/shane/deepHAR/eval/analysisScript/18janfANOVAresults/18janPAMAPRNNSBS4/variableImportances.txtreplaced.txt"
makePieChartFromFanovaOutput(file1)
```